// STANDARD costants
// nuts constants
DN_NUT_REGULAR = "DIN934";
DN_NUT_SQUARE = "DIN562";
DN_NUT_NYLOCK = "DIN985";
DN_NUT_THIN = "DIN439";

// screws constants
DN_SCREW_PHILLIP = "LUXPZ";

// bolts constants
DN_BOLT_SLOTTED_HEAD = "DIN84A";
DN_BOLT_HEX_HEAD = "DIN933";
DN_BOLT_HEX = "DIN912";

