// STANDARD costants
// nuts constants
DN_REGULAR_NUT = "DIN934";
DN_SQUARE_NUT = "DIN562";
DN_NYLOCK_NUT = "DIN985";
DN_THIN_NUT = "DIN439";

// screws and bolts constants
DN_PHILLIPS_SCREW = "LUXPZ";
DN_SLOTTED_HEAD_BOLT = "DIN84A";
DN_HEX_HEAD_BOLT = "DIN933";

